# Database
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/pwa_bd?useSSL=false&characterEncoding=utf8
spring.datasource.username=root
spring.datasource.password=rootroot
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximumPoolSize=3
spring.messages.basename=lang/messages
# SMTP Mail
mail.host=smtp.gmail.com
mail.username=tgkMailInformer@gmail.com
mail.from=tgkMailInformer@gmail.com
mail.password=tgkMailInformer1%
mail.port=587
mail.protocol=smtp
mail.debug=false
mail.defaultEncoding=UTF-8
# Spring file size limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB
project.manager.photo.dir.path=C:/Users/User/Desktop/qq

